MOCK_PLANTS_SUMMARY = [
    {
        "id": "mock-plant-001",
        "latin_name": "MOCK Dracaena deremensis",
        "family": "MOCK Liliaceae",
        "category": "MOCK Dracaena"
    },
    {
        "id": "mock-fern-001",
        "latin_name": "MOCK Nephrolepis exaltata",
        "family": "MOCK Nephrolepidaceae",
        "category": "MOCK Fern"
    },
    {
        "id": "mock-succulent-001",
        "latin_name": "MOCK Echeveria elegans",
        "family": "MOCK Crassulaceae",
        "category": "MOCK Succulent"
    }
]

MOCK_PLANTS_DETAIL = {
    "mock-plant-001": {
        "id": "mock-plant-001",
        "latin_name": "MOCK Dracaena deremensis",
        "family": "MOCK Liliaceae",
        "category": "MOCK Dracaena",
        "common_name": ["MOCK Janet Craig"],
        "common_name_fr": "MOCK Janet Craig",
        "other_names": "MOCK Other Name",
        "image": "http://example.com/mock-dracaena.jpg",
        "description": "MOCK Description",
        "origin": ["MOCK Cultivar"],
        "climate": "MOCK Tropical",
        "temperature_max": {"F": 86, "C": 30},
        "temperature_min": {"F": 50, "C": 10},
        "zone": ["MOCK 11-10"],
        "watering": "MOCK Keep moist",
        "light_ideal": "MOCK Strong light",
        "light_tolerated": "MOCK Diffuse light",
        "growth": "MOCK Regular",
        "pruning": "MOCK If needed",
        "height_potential": {"M": 3.66, "CM": 366},
        "width_potential": {"M": 1.22, "CM": 122},
        "height_at_purchase": {"M": 0.91, "CM": 91},
        "width_at_purchase": {"M": 0.91, "CM": 91},
        "pot_diameter": {"M": 0.25, "CM": 25},
        "bearing": "MOCK Erect",
        "clump": None,
        "appeal": "MOCK Robustness",
        "color_of_leaf": ["MOCK Dark green"],
        "color_of_blooms": "MOCK Light green",
        "blooming_season": "MOCK Winter / Spring",
        "perfume": None,
        "style": "MOCK Bush",
        "use": ["MOCK Potted plant", "MOCK Secondary"],
        "availability": "MOCK Regular",
        "available_sizes": "MOCK 4in to 14in",
        "insects": ["MOCK Mealy bug", "MOCK Scale"],
        "disease": "MOCK N/A",
        "url": "http://example.com/mock-dracaena-detail.html"
    },
    "mock-fern-001": {
        "id": "mock-fern-001",
        "latin_name": "MOCK Nephrolepis exaltata",
        "family": "MOCK Nephrolepidaceae",
        "category": "MOCK Fern",
        "common_name": ["MOCK Boston Fern", "MOCK Sword Fern"],
        "common_name_fr": "MOCK Fougère de Boston",
        "other_names": "MOCK Boston Fern",
        "image": "http://example.com/mock-fern.jpg",
        "description": "MOCK Popular hanging fern",
        "origin": ["MOCK Tropical regions"],
        "climate": "MOCK Humid tropical",
        "temperature_max": {"F": 75, "C": 24},
        "temperature_min": {"F": 60, "C": 15},
        "zone": ["MOCK 10-11"],
        "watering": "MOCK Keep consistently moist",
        "light_ideal": "MOCK Bright indirect light",
        "light_tolerated": "MOCK Low light",
        "growth": "MOCK Fast",
        "pruning": "MOCK Remove dead fronds",
        "height_potential": {"M": 0.60, "CM": 60},
        "width_potential": {"M": 1.0, "CM": 100},
        "height_at_purchase": {"M": 0.30, "CM": 30},
        "width_at_purchase": {"M": 0.40, "CM": 40},
        "pot_diameter": {"M": 0.15, "CM": 15},
        "bearing": "MOCK Drooping",
        "clump": None,
        "appeal": "MOCK Lush foliage",
        "color_of_leaf": ["MOCK Green"],
        "color_of_blooms": None,
        "blooming_season": "MOCK Non-flowering",
        "perfume": None,
        "style": "MOCK Hanging",
        "use": ["MOCK Indoor plant", "MOCK Hanging basket"],
        "availability": "MOCK Common",
        "available_sizes": "MOCK 4in to 10in",
        "insects": ["MOCK Spider mites", "MOCK Aphids"],
        "disease": "MOCK Root rot",
        "url": "http://example.com/mock-fern-detail.html"
    },
    "mock-succulent-001": {
        "id": "mock-succulent-001",
        "latin_name": "MOCK Echeveria elegans",
        "family": "MOCK Crassulaceae",
        "category": "MOCK Succulent",
        "common_name": ["MOCK Mexican Snow Ball", "MOCK White Mexican Rose"],
        "common_name_fr": "MOCK Rose du Mexique",
        "other_names": "MOCK Mexican Gem",
        "image": "http://example.com/mock-succulent.jpg",
        "description": "MOCK Beautiful blue-green rosette succulent",
        "origin": ["MOCK Mexico"],
        "climate": "MOCK Arid",
        "temperature_max": {"F": 80, "C": 27},
        "temperature_min": {"F": 50, "C": 10},
        "zone": ["MOCK 9-11"],
        "watering": "MOCK Water when dry",
        "light_ideal": "MOCK Bright direct light",
        "light_tolerated": "MOCK Partial shade",
        "growth": "MOCK Slow",
        "pruning": "MOCK Remove spent flowers",
        "height_potential": {"M": 0.12, "CM": 12},
        "width_potential": {"M": 0.15, "CM": 15},
        "height_at_purchase": {"M": 0.08, "CM": 8},
        "width_at_purchase": {"M": 0.10, "CM": 10},
        "pot_diameter": {"M": 0.08, "CM": 8},
        "bearing": "MOCK Compact",
        "clump": None,
        "appeal": "MOCK Architectural form",
        "color_of_leaf": ["MOCK Blue-green", "MOCK Silver"],
        "color_of_blooms": "MOCK Pink",
        "blooming_season": "MOCK Spring",
        "perfume": None,
        "style": "MOCK Rosette",
        "use": ["MOCK Indoor plant", "MOCK Rock garden"],
        "availability": "MOCK Common",
        "available_sizes": "MOCK 2in to 6in",
        "insects": ["MOCK Mealybugs"],
        "disease": "MOCK N/A",
        "url": "http://example.com/mock-succulent-detail.html"
    }
}
